package com.arka._00eEnumsAndExceptions;
/*
🧩 1. Throwable:
In Java, Throwable is the superclass for all errors and exceptions.
It belongs to the java.lang package and has two main subclasses:
a)Error
b)Exception

⚠️ 2. Error:
Errors are serious problems that occur beyond the control of the programmer.
They usually indicate issues with the system environment (like memory, JVM failure, etc.).
Errors cannot be recovered or handled easily in code using try-catch.

⚙️ 3. Exception:
Exception is an unexpected event that disrupts the normal flow of a program.It is
an object which is thrown at runtime.It occurs at runtime and can be handled using try, catch, and finally blocks.
All exceptions inherit from the Exception class.

What is Exception :-
1. Java Exception is an object that describes an exceptional (i.e., error) condition
   that has occurred in a piece of code.
2. When an exceptional condition arises, an object representing that exception is created
   and thrown in the method that caused the error.
3. At some point exception can be caught and processed.
4. Exception can be generated by Java Runtime system, or they can be manually generated by
   our code.
Java Exception Handling :-
Java exception handling is managed via five keywords:
	  i) try
	 ii) catch
	iii) throw
	 iv) throws
	  v) finally
Exception Types:
Exception types are subclasses of built in class Throwable.
Exception present in java.lang package.
Subclasses of Throwable are , i) Exception and ii) Error


Types of Exceptions =>
🔴Checked Exceptions:
These exceptions are checked at compile time by the compiler.
The programmer must handle them using a try-catch block or declare them using the throws keyword.
They usually occur due to external factors such as file handling, database issues, or network errors.
If not handled, the program will not compile.
Common examples: IOException, SQLException, ClassNotFoundException.
Also known as compile-time exceptions.

🔵Unchecked Exceptions:
These exceptions are not checked at compile time; they occur at runtime.
The compiler does not force the programmer to handle them.
They generally happen due to logical or programming errors.
If not handled, the program will compile successfully but may crash during execution.
Common examples: NullPointerException, ArithmeticException, ArrayIndexOutOfBoundsException.
Also known as runtime exceptions.                                                                                                                                    | Known as **runtime exceptions**.                                                                                                                       |

🧭Exception & Error Hierarchy Chart
Throwable is the only class in Java whose name ends with “able” and is actually a class.
Other Java terms ending with “able” — such as Runnable, Callable, and Serializable — are interfaces, not classes.
java.lang.Object
│
└── java.lang.Throwable
    │
    ├── java.lang.Error                                   (Unchecked)
    │   │
    │   ├── java.lang.VirtualMachineError
    │   │   │
    │   │   ├── java.lang.OutOfMemoryError
    │   │   ├── java.lang.StackOverflowError
    │   │   ├── java.lang.InternalError
    │   │   └── java.lang.UnknownError
    │   │
    │   ├── java.lang.LinkageError
    │   │   │
    │   │   ├── java.lang.NoClassDefFoundError
    │   │   ├── java.lang.ClassFormatError
    │   │   └── java.lang.UnsatisfiedLinkError
    │   │
    │   ├── java.lang.AssertionError
    │   │
    │   └── java.io.IOError
    │
    └── java.lang.Exception                               (Mostly Checked)
        │
        ├── java.lang.RuntimeException                    (Unchecked)
        │   │
        │   ├── java.lang.ArithmeticException
        │   ├── java.lang.NullPointerException
        │   ├── java.lang.ArrayIndexOutOfBoundsException
        │   ├── java.lang.StringIndexOutOfBoundsException
        │   ├── java.lang.NumberFormatException
        │   ├── java.lang.IllegalArgumentException
        │   ├── java.lang.IllegalStateException
        │   ├── java.lang.ClassCastException
        │   ├── java.lang.UnsupportedOperationException
        │   └── java.util.InputMismatchException
        │
        ├── java.io.IOException                           (Checked)
        │   │
        │   ├── java.io.FileNotFoundException
        │   ├── java.io.EOFException
        │   └── java.io.InterruptedIOException
        │
        ├── java.sql.SQLException                         (Checked)
        │
        ├── java.lang.ClassNotFoundException               (Checked)
        ├── java.lang.InterruptedException                 (Checked)
        ├── java.lang.CloneNotSupportedException            (Checked)
        ├── java.lang.InstantiationException                (Checked)
        ├── java.lang.reflect.InvocationTargetException    (Checked)
        ├── java.net.SocketException                       (Checked)
        ├── java.net.UnknownHostException                  (Checked)
        ├── java.net.MalformedURLException                 (Checked)
        └── java.text.ParseException                       (Checked)



 */
public class _07ExceptionHandlingDemo {
    static void subroutine(){
        int d = 0;
        int a = 50/d;
        System.out.println("a is : " + a);
    }
    public static void main(String[] args) {
        //A stack trace is what JVM prints when an exception is NOT handled.
        //The chain of method calls (stack)
        //This is for debugging, not handling.
//            subroutine();//Stack Trace
            int i=0;
            int j=0;
            int[] nums = new int[5];
            try{
                j = 18/i; //critical statement
                System.out.println(nums[0]);
                System.out.println(nums[1]);
                System.out.println(nums[4]);
//                System.out.println(nums[5]);
            } catch (Exception e) {
                System.out.println("something went wrong.." + e.getMessage());
                StackTraceElement[] stackTrace = e.getStackTrace();
                for (int i1 = 0; i1 < stackTrace.length; i1++) {
                    System.out.println(stackTrace[i1]);
                }
//                e.printStackTrace();
            }
            System.out.println(j);
            System.out.println("bye idc");
    }
}
